### ISSUE TITLE
no space left on device

### ISSUE THREAD

**Issue by GrimmjowNa** [GrimmjowNa/web-checklist#11]
```
nick@nick:~/nick/vt/web$ npm run serve

> web@0.1.0 serve /home/nick/nick/vt/web
> vue-cli-service serve

 INFO  Starting development server...
 10% building 1/1 modules 0 activeevents.js:167                              
      throw er; // Unhandled 'error' event
      ^

Error: ENOSPC: no space left on device, watch '/home/nick/nick/vt/web/public'
    at FSWatcher.start (internal/fs/watchers.js:161:26)
    at Object.watch (fs.js:1227:11)
    at createFsWatchInstance (/home/nick/nick/vt/web/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/nick/nick/vt/web/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/nick/nick/vt/web/node_modules/chokidar/lib/nodefs-handler.js:232:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/nick/nick/vt/web/node_modules/chokidar/lib/nodefs-handler.js:414:19)
    at FSWatcher.<anonymous> (/home/nick/nick/vt/web/node_modules/chokidar/lib/nodefs-handler.js:462:19)
    at FSWatcher.<anonymous> (/home/nick/nick/vt/web/node_modules/chokidar/lib/nodefs-handler.js:467:16)
    at FSReqWrap.oncomplete (fs.js:159:5)
Emitted 'error' event at:
    at FSWatcher._handleError (/home/nick/nick/vt/web/node_modules/chokidar/index.js:260:10)
    at createFsWatchInstance (/home/nick/nick/vt/web/node_modules/chokidar/lib/nodefs-handler.js:39:5)
    at setFsWatchListener (/home/nick/nick/vt/web/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    [... lines matching original stack trace ...]
    at FSReqWrap.oncomplete (fs.js:159:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nick/.npm/_logs/2018-12-17T14_36_22_263Z-debug.log
```

**Comment by GrimmjowNa** [comment]
linux中创建一个文件不仅仅需要存储空间，也需要Inode节点。Inode节点在磁盘建立的时候就分配好最大的个数（每2K空间分配一个节点），一般情况下这个数目是够用的，但是如果磁盘拥有大量小文件(小于2k)，就能将Inode节点用完。

**Comment by GrimmjowNa** [comment]
```
$cat /proc/sys/fs/inotify/max_user_watches
$echo 16384 | sudo tee -a /proc/sys/fs/inotify/max_user_watches
```

[參考](https://www.cnblogs.com/yasmi/p/5192694.html)
